name: Run Build req

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build binary
      run: |
        echo ${date} >> demo.txt
        cat demo.txt

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-binary
        path: demo.txt

  test:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Download binary artifact
        uses: actions/download-artifact@v2
        with:
          name: my-binary
  
      - name: Run tests on downloaded binary
        run: |
          cat my-binary
          ls -R
