name: Build-Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build binary
      run: |
        echo "demo" >> demo.txt

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-binary
        path: demo.txt
