name: ckb download md5 

on: 
  workflow_dispatch:
    inputs:
      ckb_version:
          description: 'ckb version'
          required: false
          default: 'v0.113.0' # 设置默认值

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  CKB_CLI_VERSION: v1.6.0

jobs:
  package-for-linux:
    name: package-for-linux
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - rel_pkg: "x86_64-unknown-linux-gnu.tar.gz"
            build_target: "prod"
          - rel_pkg: "x86_64-unknown-linux-gnu-portable.tar.gz"
            build_target: "prod_portable"
    steps:
    - uses: actions/checkout@v3
      with:
          ref: ${{ github.event.inputs.ckb_version }}
          repository: nervosnetwork/ckb
    - name: Set Env
      run: |
        export GIT_TAG_NAME=` echo ${{ github.ref }} | awk -F '/' '{print $4}' `
        echo "GIT_TAG_NAME=$GIT_TAG_NAME" >> $GITHUB_ENV
    - name: Build CKB and Package CKB
      run: |
        build_md5=$(md5sum "ckb" | awk '{print $1}')
        wget https://github.com/nervosnetwork/ckb/releases/download/${CKB_VERSION}/ckb_${CKB_VERSION}_x86_64-unknown-linux-gnu.tar.gz
        tar -zxvf ckb_${CKB_VERSION}_x86_64-unknown-linux-gnu.tar.gz
        wget_md5=$(md5sum "ckb_${CKB_VERSION}_x86_64-unknown-linux-gnu/ckb" | awk '{print $1}')
        echo "md5:"$wget_md5

    env:
      BUILDER_IMAGE: nervos/ckb-docker-builder:bionic-rust-1.71.1-openssl-3.1.3
      REL_PKG: ${{ matrix.rel_pkg }}
      CKB_VERSION: ${{ github.event.inputs.ckb_version }}
