name: ckb build test 

on: 
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: v0.113.0
          repository: nervosnetwork/ckb

      - name: Install project dependencies and build
        run: |
          cd /home/runner/work/test-action/test-action
          docker run --rm -i -w /ckb -v $(pwd):/ckb -e OPENSSL_STATIC=1 -e OPENSSL_LIB_DIR=/usr/local/lib64 -e OPENSSL_INCLUDE_DIR=/usr/local/include nervos/ckb-docker-builder:centos-7-rust-1.71.1-openssl-3.1.3 make prod
          cd target/prod
          md5sum ckb
