name: easy-bilibili-daily-task

on:
  schedule:
    - cron: '27/6 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: echo "This step will always run"
