name: Highlight example

on: 
  workflow_dispatch:


jobs:
  highlight:
  
    runs-on: ubuntu-latest
    env:
      SSH_ID: ${{ secrets.TEST }}
    steps:
      - name: Highlight text in HTML
        run: |
          echo $SSH_ID > demo.log 
          cat demo.log
          IFS=' ' read -ra elements <<< "$SSH_ID"
          for element in "${elements[@]}"; do
            echo "$element" >> output.txt
          done
          cat output.txt
      - name: Setup upterm session
        if: ${{ always() }}
        uses: lhotari/action-upterm@v1
