name: Highlight example

on: 
  workflow_dispatch:


jobs:
  highlight:
    runs-on: ubuntu-latest
    steps:
      - name: Highlight text in HTML
        run: |
          echo ${{ secrets.TEST }} > demo.log 
          cat demo.log
      
      - name: Setup upterm session
        if: ${{ always() }}
        uses: lhotari/action-upterm@v1
