name: Highlight example

on: 
  workflow_dispatch:


jobs:
  highlight:
  
    runs-on: ubuntu-latest
    env:
      SSH_ID: ${{ secrets.TEST }}
    steps:
      - name: Highlight text in HTML
        run: |
          echo $SSH_ID > demo.log 
          cat demo.log
      - name: Setup upterm session
        if: ${{ always() }}
        uses: lhotari/action-upterm@v1
