name: nexus test 

on: 
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: main
          repository: gpBlockchain/nexus-e2e
          path: nexus-e2e

      - uses: actions/checkout@v3
        with:
          ref: main
          repository: homura/nexus
          submodules: recursive
          path: nexus

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: restore dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
        
      - name: Install project dependencies and build
        run: |
          cd /home/runner/work/test-action/test-action/nexus 
          npm install

      - name: Build packages
        run: |
          cd /home/runner/work/test-action/test-action/nexus 
          npm run build
      - name: cp nexus build 
        run: | 
          rm -rf /home/runner/work/test-action/test-action/nexus-e2e/packages/e2e/build
          cp -r /home/runner/work/test-action/test-action/nexus/packages/extension-chrome/build /home/runner/work/test-action/test-action/nexus-e2e/packages/e2e/ 
      - name: start nexus web web
        id: startWeb
        if: success() || failure()        
        run: |
          cd /home/runner/work/test-action/test-action/nexus-e2e/packages/nexus-web
          npm i
          npm run start > node.log 2>&1 &
      - name: test
        id: test
        if: success() || failure()        
        run: |
          cd /home/runner/work/test-action/test-action/nexus-e2e/packages/e2e
          npm i
          xvfb-run --auto-servernum npm run test

      - name: make update file  dir
        if: success() || failure()
        run: |	  	
          mkdir /home/runner/work/test-action/test-action/reportAndNexus

      - name: cp nexus file to update file 
        if: success() || failure()
        run: |	  	        
          tar -zcvf /home/runner/work/test-action/test-action/reportAndNexus/build.tar.gz /home/runner/work/test-action/test-action/nexus/packages/extension-chrome/build
          
      - name: package report
        id: package
        if: success() || failure()
        run: |
          tar -zcvf /home/runner/work/test-action/test-action/reportAndNexus/allure-results.tar.gz  /home/runner/work/test-action/test-action/nexus-e2e/packages/e2e/allure-results

      - name: Publish e2e test report and nexus build 
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: jfoa-build-reports-${{ runner.os }}
          path: /home/runner/work/test-action/test-action/reportAndNexus

