
name: nexus test 

on: 
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          ref: main
          repository: gpBlockchain/nexus-e2e
          path: nexus-e2e

      - uses: actions/checkout@v3
        with:
          ref: main
          repository: ckb-js/nexus
          submodules: recursive
          path: nexus

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: restore dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: cat msg 
        run: |
          pwd
          tree -L 2
      - name: cd nexus 
        run: cd nexus
        
      - name: Install project dependencies and build
        run: npm install

      - name: Build packages
        run: |
          npm run build

      - name: cd nexus-e2e
        run: cd  ../nexus-e2e
        
      - name: start nexus web web
        id: startWeb
        run: |
          cd packages/nexus-web
          npm i
          npm run start > node.log 2>&1 &
          cd ../../
      - name: test
        id: test
        run: |
          cd packages/e2e
          npm i
#          xvfb-run --auto-servernum npm run test
#          cd ../../        
