name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download binary artifact
      uses: actions/download-artifact@v2
      with:
        name: my-binary
        path: demo.txt   # 下载到的目标路径

    - name: Run tests on downloaded binary
      run: |
        cat demo.txt 
