name: trigger_gw_alphanet_openzeppelin_more_test


on:
  workflow_dispatch:

jobs:
  contractTestsInit:
    name: contractTestsInit
    runs-on: ubuntu-latest
    container:
      image: node:14.16    
      volumes:
        - /workspace:/github/workspace    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: godwoken-com
          repository: gpBlockchain/openzeppelin-contracts
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Node Cache
        uses: actions/cache@v2
        id: npm-and-yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('/home/runner/work/**/package-lock.json', '/home/runner/work/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
            
      - name: Run init 
        id: runtest
        run: |
          npm install
          npm run test:init
          
  RunPipeline52:
    needs: contractTestsInit
    runs-on: ubuntu-latest
    container:
      image: node:14.16        
      volumes:
        - /workspace:/github/workspace    
    steps:
      - name: run52
        id: run52
        run: |
          cd /home/runner/work/test-action/test-action/
          npm run test:pipeline5-2
          
  PublishReports:
    needs: contractTestsInit  
    runs-on: ubuntu-latest
    container:
      image: node:14.16    
      volumes:
        - /workspace:/github/workspace   
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: jfoa-build-reports-${{ runner.os }}
          path: mochawesome-report/
